version: "3.4"

services:
  elasticsearch:
    build:
      context: elasticsearch
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms256m
      ELASTIC_PASSWORD: elastic123
    networks:
      - elk_net

  logstash:
    build:
      context: logstash
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - type: bind
        source: ./logstash/monitoring
        target: /usr/share/logstash/monitoring
      - type: bind
        source: ./logstash/pipelines.yml
        target: /usr/share/logstash/config/pipelines.yml
      - type: bind
        source: ./logstash/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
      - type: bind
        source: ./logstash/logstash.yaml
        target: /tmp/config/logstash.yaml
    ports:
      - 5000:5000
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xmx1g -Xms256m
    networks:
      - elk_net
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana
      args:
        ELK_VERSION: 7.8.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - 5601:5601
    networks:
      - elk_net
    depends_on:
      - elasticsearch


networks:
  elk_net:
    driver: bridge

volumes:
  elasticsearch:
    driver: local